name: Build and Test
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build

      - name: Test built site using html-validate for W3C check
        run: npm run test
